# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: community/group/v1/group_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'community/group/v1/group_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&community/group/v1/group_service.proto\x12\x16\x61kiora.community.group\"4\n\x12\x43reateGroupRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\\\n\x11PatchGroupRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tadd_users\x18\x03 \x03(\t\x12\x14\n\x0c\x64\x65lete_users\x18\x04 \x03(\t\"J\n\rGroupResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05users\x18\x04 \x03(\t\"\x1d\n\x0fGetGroupRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xad\x02\n\x0cGroupService\x12`\n\x0b\x43reateGroup\x12*.akiora.community.group.CreateGroupRequest\x1a%.akiora.community.group.GroupResponse\x12_\n\x0bUpdateGroup\x12).akiora.community.group.PatchGroupRequest\x1a%.akiora.community.group.GroupResponse\x12Z\n\x08GetGroup\x12\'.akiora.community.group.GetGroupRequest\x1a%.akiora.community.group.GroupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'community.group.v1.group_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEGROUPREQUEST']._serialized_start=66
  _globals['_CREATEGROUPREQUEST']._serialized_end=118
  _globals['_PATCHGROUPREQUEST']._serialized_start=120
  _globals['_PATCHGROUPREQUEST']._serialized_end=212
  _globals['_GROUPRESPONSE']._serialized_start=214
  _globals['_GROUPRESPONSE']._serialized_end=288
  _globals['_GETGROUPREQUEST']._serialized_start=290
  _globals['_GETGROUPREQUEST']._serialized_end=319
  _globals['_GROUPSERVICE']._serialized_start=322
  _globals['_GROUPSERVICE']._serialized_end=623
# @@protoc_insertion_point(module_scope)
