# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from community.group.v1 import group_service_pb2 as community_dot_group_dot_v1_dot_group__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in community/group/v1/group_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGroup = channel.unary_unary(
                '/akiora.community.group.GroupService/CreateGroup',
                request_serializer=community_dot_group_dot_v1_dot_group__service__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=community_dot_group_dot_v1_dot_group__service__pb2.GroupResponse.FromString,
                _registered_method=True)
        self.UpdateGroup = channel.unary_unary(
                '/akiora.community.group.GroupService/UpdateGroup',
                request_serializer=community_dot_group_dot_v1_dot_group__service__pb2.PatchGroupRequest.SerializeToString,
                response_deserializer=community_dot_group_dot_v1_dot_group__service__pb2.GroupResponse.FromString,
                _registered_method=True)
        self.GetGroup = channel.unary_unary(
                '/akiora.community.group.GroupService/GetGroup',
                request_serializer=community_dot_group_dot_v1_dot_group__service__pb2.GetGroupRequest.SerializeToString,
                response_deserializer=community_dot_group_dot_v1_dot_group__service__pb2.GroupResponse.FromString,
                _registered_method=True)


class GroupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=community_dot_group_dot_v1_dot_group__service__pb2.CreateGroupRequest.FromString,
                    response_serializer=community_dot_group_dot_v1_dot_group__service__pb2.GroupResponse.SerializeToString,
            ),
            'UpdateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGroup,
                    request_deserializer=community_dot_group_dot_v1_dot_group__service__pb2.PatchGroupRequest.FromString,
                    response_serializer=community_dot_group_dot_v1_dot_group__service__pb2.GroupResponse.SerializeToString,
            ),
            'GetGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroup,
                    request_deserializer=community_dot_group_dot_v1_dot_group__service__pb2.GetGroupRequest.FromString,
                    response_serializer=community_dot_group_dot_v1_dot_group__service__pb2.GroupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akiora.community.group.GroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('akiora.community.group.GroupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.community.group.GroupService/CreateGroup',
            community_dot_group_dot_v1_dot_group__service__pb2.CreateGroupRequest.SerializeToString,
            community_dot_group_dot_v1_dot_group__service__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.community.group.GroupService/UpdateGroup',
            community_dot_group_dot_v1_dot_group__service__pb2.PatchGroupRequest.SerializeToString,
            community_dot_group_dot_v1_dot_group__service__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.community.group.GroupService/GetGroup',
            community_dot_group_dot_v1_dot_group__service__pb2.GetGroupRequest.SerializeToString,
            community_dot_group_dot_v1_dot_group__service__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
