/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MessengerRouteImport } from './routes/messenger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as GameseriesIdRouteImport } from './routes/gameseries.$id'
import { Route as GameseriesIdIndexRouteImport } from './routes/gameseries.$id.index'
import { Route as GameseriesIdResultsRouteImport } from './routes/gameseries.$id.results'
import { Route as GameseriesIdDraftRouteImport } from './routes/gameseries.$id.draft'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MessengerRoute = MessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TournamentsRoute,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TournamentsRoute,
} as any)
const GameseriesIdRoute = GameseriesIdRouteImport.update({
  id: '/gameseries/$id',
  path: '/gameseries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameseriesIdIndexRoute = GameseriesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameseriesIdRoute,
} as any)
const GameseriesIdResultsRoute = GameseriesIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => GameseriesIdRoute,
} as any)
const GameseriesIdDraftRoute = GameseriesIdDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => GameseriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/messenger': typeof MessengerRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/gameseries/$id': typeof GameseriesIdRouteWithChildren
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/gameseries/$id/draft': typeof GameseriesIdDraftRoute
  '/gameseries/$id/results': typeof GameseriesIdResultsRoute
  '/gameseries/$id/': typeof GameseriesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/messenger': typeof MessengerRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/gameseries/$id/draft': typeof GameseriesIdDraftRoute
  '/gameseries/$id/results': typeof GameseriesIdResultsRoute
  '/gameseries/$id': typeof GameseriesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/messenger': typeof MessengerRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/gameseries/$id': typeof GameseriesIdRouteWithChildren
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/gameseries/$id/draft': typeof GameseriesIdDraftRoute
  '/gameseries/$id/results': typeof GameseriesIdResultsRoute
  '/gameseries/$id/': typeof GameseriesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/community'
    | '/login'
    | '/messenger'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/tournaments'
    | '/gameseries/$id'
    | '/tournaments/$id'
    | '/tournaments/'
    | '/gameseries/$id/draft'
    | '/gameseries/$id/results'
    | '/gameseries/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/community'
    | '/login'
    | '/messenger'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/tournaments/$id'
    | '/tournaments'
    | '/gameseries/$id/draft'
    | '/gameseries/$id/results'
    | '/gameseries/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/community'
    | '/login'
    | '/messenger'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/tournaments'
    | '/gameseries/$id'
    | '/tournaments/$id'
    | '/tournaments/'
    | '/gameseries/$id/draft'
    | '/gameseries/$id/results'
    | '/gameseries/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  LoginRoute: typeof LoginRoute
  MessengerRoute: typeof MessengerRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  GameseriesIdRoute: typeof GameseriesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messenger': {
      id: '/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof MessengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/gameseries/$id': {
      id: '/gameseries/$id'
      path: '/gameseries/$id'
      fullPath: '/gameseries/$id'
      preLoaderRoute: typeof GameseriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gameseries/$id/': {
      id: '/gameseries/$id/'
      path: '/'
      fullPath: '/gameseries/$id/'
      preLoaderRoute: typeof GameseriesIdIndexRouteImport
      parentRoute: typeof GameseriesIdRoute
    }
    '/gameseries/$id/results': {
      id: '/gameseries/$id/results'
      path: '/results'
      fullPath: '/gameseries/$id/results'
      preLoaderRoute: typeof GameseriesIdResultsRouteImport
      parentRoute: typeof GameseriesIdRoute
    }
    '/gameseries/$id/draft': {
      id: '/gameseries/$id/draft'
      path: '/draft'
      fullPath: '/gameseries/$id/draft'
      preLoaderRoute: typeof GameseriesIdDraftRouteImport
      parentRoute: typeof GameseriesIdRoute
    }
  }
}

interface TournamentsRouteChildren {
  TournamentsIdRoute: typeof TournamentsIdRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsIdRoute: TournamentsIdRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

interface GameseriesIdRouteChildren {
  GameseriesIdDraftRoute: typeof GameseriesIdDraftRoute
  GameseriesIdResultsRoute: typeof GameseriesIdResultsRoute
  GameseriesIdIndexRoute: typeof GameseriesIdIndexRoute
}

const GameseriesIdRouteChildren: GameseriesIdRouteChildren = {
  GameseriesIdDraftRoute: GameseriesIdDraftRoute,
  GameseriesIdResultsRoute: GameseriesIdResultsRoute,
  GameseriesIdIndexRoute: GameseriesIdIndexRoute,
}

const GameseriesIdRouteWithChildren = GameseriesIdRoute._addFileChildren(
  GameseriesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  LoginRoute: LoginRoute,
  MessengerRoute: MessengerRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  GameseriesIdRoute: GameseriesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
