# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game/v1/gameseries_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'game/v1/gameseries_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import http_pb2 as google_dot_api_dot_http__pb2
from common import game_actors_pb2 as common_dot_game__actors__pb2
from common import game_settings_pb2 as common_dot_game__settings__pb2
from common import game_draft_pb2 as common_dot_game__draft__pb2
from common import types_pb2 as common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n game/v1/gameseries_service.proto\x12\x16\x61kiora.game.gameseries\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\x1a\x18\x63ommon/game_actors.proto\x1a\x1a\x63ommon/game_settings.proto\x1a\x17\x63ommon/game_draft.proto\x1a\x12\x63ommon/types.proto\"L\n\x12ToggleReadyRequest\x12\x11\n\tseries_id\x18\x01 \x01(\t\x12#\n\x05\x61\x63tor\x18\x02 \x01(\x0b\x32\x14.akiora.common.Actor\"P\n\x12\x44raftActionRequest\x12\x11\n\tseries_id\x18\x01 \x01(\t\x12\'\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x16.akiora.common.Command\"S\n\x10\x43hampLockRequest\x12\x11\n\tseries_id\x18\x01 \x01(\t\x12,\n\nchamp_lock\x18\x02 \x01(\x0b\x32\x18.akiora.common.ChampLock2\x99\x02\n\x11GameSeriesService\x12\x84\x01\n\x0b\x44raftAction\x12*.akiora.game.gameseries.DraftActionRequest\x1a\x14.akiora.common.Empty\"3\x82\xd3\xe4\x93\x02-\"(/v1/game-series/{series_id}/draft/action:\x01*\x12}\n\x0bToggleReady\x12*.akiora.game.gameseries.ToggleReadyRequest\x1a\x14.akiora.common.Empty\",\x82\xd3\xe4\x93\x02&\"!/v1/game-series/{series_id}/ready:\x01*B\x18Z\x16\x61kiora/game/gameseriesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game.v1.gameseries_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026akiora/game/gameseries'
  _globals['_GAMESERIESSERVICE'].methods_by_name['DraftAction']._loaded_options = None
  _globals['_GAMESERIESSERVICE'].methods_by_name['DraftAction']._serialized_options = b'\202\323\344\223\002-\"(/v1/game-series/{series_id}/draft/action:\001*'
  _globals['_GAMESERIESSERVICE'].methods_by_name['ToggleReady']._loaded_options = None
  _globals['_GAMESERIESSERVICE'].methods_by_name['ToggleReady']._serialized_options = b'\202\323\344\223\002&\"!/v1/game-series/{series_id}/ready:\001*'
  _globals['_TOGGLEREADYREQUEST']._serialized_start=212
  _globals['_TOGGLEREADYREQUEST']._serialized_end=288
  _globals['_DRAFTACTIONREQUEST']._serialized_start=290
  _globals['_DRAFTACTIONREQUEST']._serialized_end=370
  _globals['_CHAMPLOCKREQUEST']._serialized_start=372
  _globals['_CHAMPLOCKREQUEST']._serialized_end=455
  _globals['_GAMESERIESSERVICE']._serialized_start=458
  _globals['_GAMESERIESSERVICE']._serialized_end=739
# @@protoc_insertion_point(module_scope)
