# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/game_draft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/game_draft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import game_actors_pb2 as common_dot_game__actors__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ommon/game_draft.proto\x12\rakiora.common\x1a\x18\x63ommon/game_actors.proto\"U\n\x07\x43ommand\x12#\n\x05\x61\x63tor\x18\x01 \x01(\x0b\x32\x14.akiora.common.Actor\x12%\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x15.akiora.common.Action\"6\n\x06\x41\x63tion\x12\x0e\n\x04pick\x18\x01 \x01(\x05H\x00\x12\r\n\x03\x62\x61n\x18\x02 \x01(\x05H\x00\x42\r\n\x0b\x61\x63tion_type\"3\n\tChampLock\x12\x13\n\x0b\x63hampion_id\x18\x01 \x01(\x05\x12\x11\n\tplayer_id\x18\x02 \x01(\tB\x0fZ\rakiora/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.game_draft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rakiora/common'
  _globals['_COMMAND']._serialized_start=68
  _globals['_COMMAND']._serialized_end=153
  _globals['_ACTION']._serialized_start=155
  _globals['_ACTION']._serialized_end=209
  _globals['_CHAMPLOCK']._serialized_start=211
  _globals['_CHAMPLOCK']._serialized_end=262
# @@protoc_insertion_point(module_scope)
