# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.api.serviceusage.v1beta1 import resources_pb2 as google_dot_api_dot_serviceusage_dot_v1beta1_dot_resources__pb2
from google.api.serviceusage.v1beta1 import serviceusage_pb2 as google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2
from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/api/serviceusage/v1beta1/serviceusage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceUsageStub(object):
    """[Service Usage API](https://cloud.google.com/service-usage/docs/overview)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnableService = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/EnableService',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.EnableServiceRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.DisableService = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/DisableService',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.DisableServiceRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.GetService = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/GetService',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GetServiceRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_resources__pb2.Service.FromString,
                _registered_method=True)
        self.ListServices = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/ListServices',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListServicesRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListServicesResponse.FromString,
                _registered_method=True)
        self.BatchEnableServices = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/BatchEnableServices',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.BatchEnableServicesRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.ListConsumerQuotaMetrics = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/ListConsumerQuotaMetrics',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerQuotaMetricsRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerQuotaMetricsResponse.FromString,
                _registered_method=True)
        self.GetConsumerQuotaMetric = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/GetConsumerQuotaMetric',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GetConsumerQuotaMetricRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_resources__pb2.ConsumerQuotaMetric.FromString,
                _registered_method=True)
        self.GetConsumerQuotaLimit = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/GetConsumerQuotaLimit',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GetConsumerQuotaLimitRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_resources__pb2.ConsumerQuotaLimit.FromString,
                _registered_method=True)
        self.CreateAdminOverride = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/CreateAdminOverride',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.CreateAdminOverrideRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.UpdateAdminOverride = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/UpdateAdminOverride',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.UpdateAdminOverrideRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.DeleteAdminOverride = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/DeleteAdminOverride',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.DeleteAdminOverrideRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.ListAdminOverrides = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/ListAdminOverrides',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListAdminOverridesRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListAdminOverridesResponse.FromString,
                _registered_method=True)
        self.ImportAdminOverrides = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/ImportAdminOverrides',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ImportAdminOverridesRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.CreateConsumerOverride = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/CreateConsumerOverride',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.CreateConsumerOverrideRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.UpdateConsumerOverride = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/UpdateConsumerOverride',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.UpdateConsumerOverrideRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.DeleteConsumerOverride = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/DeleteConsumerOverride',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.DeleteConsumerOverrideRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.ListConsumerOverrides = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/ListConsumerOverrides',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerOverridesRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerOverridesResponse.FromString,
                _registered_method=True)
        self.ImportConsumerOverrides = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/ImportConsumerOverrides',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ImportConsumerOverridesRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.GenerateServiceIdentity = channel.unary_unary(
                '/google.api.serviceusage.v1beta1.ServiceUsage/GenerateServiceIdentity',
                request_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GenerateServiceIdentityRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)


class ServiceUsageServicer(object):
    """[Service Usage API](https://cloud.google.com/service-usage/docs/overview)
    """

    def EnableService(self, request, context):
        """Enables a service so that it can be used with a project.

        Operation response type: `google.protobuf.Empty`
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableService(self, request, context):
        """Disables a service so that it can no longer be used with a project.
        This prevents unintended usage that may cause unexpected billing
        charges or security leaks.

        It is not valid to call the disable method on a service that is not
        currently enabled. Callers will receive a `FAILED_PRECONDITION` status if
        the target service is not currently enabled.

        Operation response type: `google.protobuf.Empty`
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetService(self, request, context):
        """Returns the service configuration and enabled state for a given service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServices(self, request, context):
        """Lists all services available to the specified project, and the current
        state of those services with respect to the project. The list includes
        all public services, all services for which the calling user has the
        `servicemanagement.services.bind` permission, and all services that have
        already been enabled on the project. The list can be filtered to
        only include services in a specific state, for example to only include
        services enabled on the project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchEnableServices(self, request, context):
        """Enables multiple services on a project. The operation is atomic: if
        enabling any service fails, then the entire batch fails, and no state
        changes occur.

        Operation response type: `google.protobuf.Empty`
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConsumerQuotaMetrics(self, request, context):
        """Retrieves a summary of all quota information visible to the service
        consumer, organized by service metric. Each metric includes information
        about all of its defined limits. Each limit includes the limit
        configuration (quota unit, preciseness, default value), the current
        effective limit value, and all of the overrides applied to the limit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsumerQuotaMetric(self, request, context):
        """Retrieves a summary of quota information for a specific quota metric
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsumerQuotaLimit(self, request, context):
        """Retrieves a summary of quota information for a specific quota limit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAdminOverride(self, request, context):
        """Creates an admin override.
        An admin override is applied by an administrator of a parent folder or
        parent organization of the consumer receiving the override. An admin
        override is intended to limit the amount of quota the consumer can use out
        of the total quota pool allocated to all children of the folder or
        organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAdminOverride(self, request, context):
        """Updates an admin override.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAdminOverride(self, request, context):
        """Deletes an admin override.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAdminOverrides(self, request, context):
        """Lists all admin overrides on this limit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportAdminOverrides(self, request, context):
        """Creates or updates multiple admin overrides atomically, all on the
        same consumer, but on many different metrics or limits.
        The name field in the quota override message should not be set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConsumerOverride(self, request, context):
        """Creates a consumer override.
        A consumer override is applied to the consumer on its own authority to
        limit its own quota usage. Consumer overrides cannot be used to grant more
        quota than would be allowed by admin overrides, producer overrides, or the
        default limit of the service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConsumerOverride(self, request, context):
        """Updates a consumer override.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConsumerOverride(self, request, context):
        """Deletes a consumer override.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConsumerOverrides(self, request, context):
        """Lists all consumer overrides on this limit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportConsumerOverrides(self, request, context):
        """Creates or updates multiple consumer overrides atomically, all on the
        same consumer, but on many different metrics or limits.
        The name field in the quota override message should not be set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateServiceIdentity(self, request, context):
        """Generates service identity for service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceUsageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnableService': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableService,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.EnableServiceRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DisableService': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableService,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.DisableServiceRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'GetService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetService,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GetServiceRequest.FromString,
                    response_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_resources__pb2.Service.SerializeToString,
            ),
            'ListServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServices,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListServicesRequest.FromString,
                    response_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListServicesResponse.SerializeToString,
            ),
            'BatchEnableServices': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchEnableServices,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.BatchEnableServicesRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListConsumerQuotaMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConsumerQuotaMetrics,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerQuotaMetricsRequest.FromString,
                    response_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerQuotaMetricsResponse.SerializeToString,
            ),
            'GetConsumerQuotaMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsumerQuotaMetric,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GetConsumerQuotaMetricRequest.FromString,
                    response_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_resources__pb2.ConsumerQuotaMetric.SerializeToString,
            ),
            'GetConsumerQuotaLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsumerQuotaLimit,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GetConsumerQuotaLimitRequest.FromString,
                    response_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_resources__pb2.ConsumerQuotaLimit.SerializeToString,
            ),
            'CreateAdminOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAdminOverride,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.CreateAdminOverrideRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateAdminOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAdminOverride,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.UpdateAdminOverrideRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteAdminOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAdminOverride,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.DeleteAdminOverrideRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListAdminOverrides': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAdminOverrides,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListAdminOverridesRequest.FromString,
                    response_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListAdminOverridesResponse.SerializeToString,
            ),
            'ImportAdminOverrides': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportAdminOverrides,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ImportAdminOverridesRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'CreateConsumerOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConsumerOverride,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.CreateConsumerOverrideRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateConsumerOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConsumerOverride,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.UpdateConsumerOverrideRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteConsumerOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConsumerOverride,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.DeleteConsumerOverrideRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListConsumerOverrides': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConsumerOverrides,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerOverridesRequest.FromString,
                    response_serializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerOverridesResponse.SerializeToString,
            ),
            'ImportConsumerOverrides': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportConsumerOverrides,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ImportConsumerOverridesRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'GenerateServiceIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateServiceIdentity,
                    request_deserializer=google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GenerateServiceIdentityRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.api.serviceusage.v1beta1.ServiceUsage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.api.serviceusage.v1beta1.ServiceUsage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceUsage(object):
    """[Service Usage API](https://cloud.google.com/service-usage/docs/overview)
    """

    @staticmethod
    def EnableService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/EnableService',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.EnableServiceRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/DisableService',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.DisableServiceRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/GetService',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GetServiceRequest.SerializeToString,
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_resources__pb2.Service.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/ListServices',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListServicesRequest.SerializeToString,
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchEnableServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/BatchEnableServices',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.BatchEnableServicesRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConsumerQuotaMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/ListConsumerQuotaMetrics',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerQuotaMetricsRequest.SerializeToString,
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerQuotaMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsumerQuotaMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/GetConsumerQuotaMetric',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GetConsumerQuotaMetricRequest.SerializeToString,
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_resources__pb2.ConsumerQuotaMetric.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsumerQuotaLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/GetConsumerQuotaLimit',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GetConsumerQuotaLimitRequest.SerializeToString,
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_resources__pb2.ConsumerQuotaLimit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAdminOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/CreateAdminOverride',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.CreateAdminOverrideRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAdminOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/UpdateAdminOverride',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.UpdateAdminOverrideRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAdminOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/DeleteAdminOverride',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.DeleteAdminOverrideRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAdminOverrides(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/ListAdminOverrides',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListAdminOverridesRequest.SerializeToString,
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListAdminOverridesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportAdminOverrides(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/ImportAdminOverrides',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ImportAdminOverridesRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConsumerOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/CreateConsumerOverride',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.CreateConsumerOverrideRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConsumerOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/UpdateConsumerOverride',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.UpdateConsumerOverrideRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConsumerOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/DeleteConsumerOverride',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.DeleteConsumerOverrideRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConsumerOverrides(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/ListConsumerOverrides',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerOverridesRequest.SerializeToString,
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ListConsumerOverridesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportConsumerOverrides(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/ImportConsumerOverrides',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.ImportConsumerOverridesRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateServiceIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.serviceusage.v1beta1.ServiceUsage/GenerateServiceIdentity',
            google_dot_api_dot_serviceusage_dot_v1beta1_dot_serviceusage__pb2.GenerateServiceIdentityRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
