include:
    - storage.yml
services:
    gameservice:
        build:
            context: .
            dockerfile: rust/services/game/Dockerfile
        container_name: gameservice
        ports:
            - "8003:50051"

        environment:
            MONGODB_URI: mongodb://mongodb:27017/?replicaSet=rs0

            MONGODB_DATABASE: game_db

        depends_on:
            - mongodb

        restart: unless-stopped

        networks:
            - backend_akiora
