# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.api.apikeys.v2 import apikeys_pb2 as google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2
from google.api.apikeys.v2 import resources_pb2 as google_dot_api_dot_apikeys_dot_v2_dot_resources__pb2
from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/api/apikeys/v2/apikeys_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApiKeysStub(object):
    """Manages the API keys associated with projects.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateKey = channel.unary_unary(
                '/google.api.apikeys.v2.ApiKeys/CreateKey',
                request_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.CreateKeyRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.ListKeys = channel.unary_unary(
                '/google.api.apikeys.v2.ApiKeys/ListKeys',
                request_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.ListKeysRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.ListKeysResponse.FromString,
                _registered_method=True)
        self.GetKey = channel.unary_unary(
                '/google.api.apikeys.v2.ApiKeys/GetKey',
                request_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.GetKeyRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_resources__pb2.Key.FromString,
                _registered_method=True)
        self.GetKeyString = channel.unary_unary(
                '/google.api.apikeys.v2.ApiKeys/GetKeyString',
                request_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.GetKeyStringRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.GetKeyStringResponse.FromString,
                _registered_method=True)
        self.UpdateKey = channel.unary_unary(
                '/google.api.apikeys.v2.ApiKeys/UpdateKey',
                request_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.UpdateKeyRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.DeleteKey = channel.unary_unary(
                '/google.api.apikeys.v2.ApiKeys/DeleteKey',
                request_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.DeleteKeyRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.UndeleteKey = channel.unary_unary(
                '/google.api.apikeys.v2.ApiKeys/UndeleteKey',
                request_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.UndeleteKeyRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                _registered_method=True)
        self.LookupKey = channel.unary_unary(
                '/google.api.apikeys.v2.ApiKeys/LookupKey',
                request_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.LookupKeyRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.LookupKeyResponse.FromString,
                _registered_method=True)


class ApiKeysServicer(object):
    """Manages the API keys associated with projects.
    """

    def CreateKey(self, request, context):
        """Creates a new API key.

        NOTE: Key is a global resource; hence the only supported value for
        location is `global`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKeys(self, request, context):
        """Lists the API keys owned by a project. The key string of the API key
        isn't included in the response.

        NOTE: Key is a global resource; hence the only supported value for
        location is `global`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKey(self, request, context):
        """Gets the metadata for an API key. The key string of the API key
        isn't included in the response.

        NOTE: Key is a global resource; hence the only supported value for
        location is `global`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKeyString(self, request, context):
        """Get the key string for an API key.

        NOTE: Key is a global resource; hence the only supported value for
        location is `global`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKey(self, request, context):
        """Patches the modifiable fields of an API key.
        The key string of the API key isn't included in the response.

        NOTE: Key is a global resource; hence the only supported value for
        location is `global`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKey(self, request, context):
        """Deletes an API key. Deleted key can be retrieved within 30 days of
        deletion. Afterward, key will be purged from the project.

        NOTE: Key is a global resource; hence the only supported value for
        location is `global`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeleteKey(self, request, context):
        """Undeletes an API key which was deleted within 30 days.

        NOTE: Key is a global resource; hence the only supported value for
        location is `global`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupKey(self, request, context):
        """Find the parent project and resource name of the API
        key that matches the key string in the request. If the API key has been
        purged, resource name will not be set.
        The service account must have the `apikeys.keys.lookup` permission
        on the parent project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiKeysServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateKey,
                    request_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.CreateKeyRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKeys,
                    request_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.ListKeysRequest.FromString,
                    response_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.ListKeysResponse.SerializeToString,
            ),
            'GetKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKey,
                    request_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.GetKeyRequest.FromString,
                    response_serializer=google_dot_api_dot_apikeys_dot_v2_dot_resources__pb2.Key.SerializeToString,
            ),
            'GetKeyString': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeyString,
                    request_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.GetKeyStringRequest.FromString,
                    response_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.GetKeyStringResponse.SerializeToString,
            ),
            'UpdateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKey,
                    request_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.UpdateKeyRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKey,
                    request_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.DeleteKeyRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UndeleteKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeleteKey,
                    request_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.UndeleteKeyRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'LookupKey': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupKey,
                    request_deserializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.LookupKeyRequest.FromString,
                    response_serializer=google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.LookupKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.api.apikeys.v2.ApiKeys', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.api.apikeys.v2.ApiKeys', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApiKeys(object):
    """Manages the API keys associated with projects.
    """

    @staticmethod
    def CreateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.apikeys.v2.ApiKeys/CreateKey',
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.CreateKeyRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.apikeys.v2.ApiKeys/ListKeys',
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.ListKeysRequest.SerializeToString,
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.ListKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.apikeys.v2.ApiKeys/GetKey',
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.GetKeyRequest.SerializeToString,
            google_dot_api_dot_apikeys_dot_v2_dot_resources__pb2.Key.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKeyString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.apikeys.v2.ApiKeys/GetKeyString',
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.GetKeyStringRequest.SerializeToString,
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.GetKeyStringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.apikeys.v2.ApiKeys/UpdateKey',
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.UpdateKeyRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.apikeys.v2.ApiKeys/DeleteKey',
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.DeleteKeyRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeleteKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.apikeys.v2.ApiKeys/UndeleteKey',
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.UndeleteKeyRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.apikeys.v2.ApiKeys/LookupKey',
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.LookupKeyRequest.SerializeToString,
            google_dot_api_dot_apikeys_dot_v2_dot_apikeys__pb2.LookupKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
