# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common import types_pb2 as common_dot_types__pb2
from messenger.v1 import messenger_service_pb2 as messenger_dot_v1_dot_messenger__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in messenger/v1/messenger_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChat = channel.unary_unary(
                '/akiora.messenger.ChatService/CreateChat',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.CreateChatRequest.SerializeToString,
                response_deserializer=messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GetChat = channel.unary_unary(
                '/akiora.messenger.ChatService/GetChat',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.GetChatRequest.SerializeToString,
                response_deserializer=messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.AddAllowedUser = channel.unary_unary(
                '/akiora.messenger.ChatService/AddAllowedUser',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.AddAllowedUserRequest.SerializeToString,
                response_deserializer=messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.RemoveAllowedUser = channel.unary_unary(
                '/akiora.messenger.ChatService/RemoveAllowedUser',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.RemoveAllowedUserRequest.SerializeToString,
                response_deserializer=common_dot_types__pb2.Empty.FromString,
                _registered_method=True)
        self.FreezeChat = channel.unary_unary(
                '/akiora.messenger.ChatService/FreezeChat',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.FreezeChatRequest.SerializeToString,
                response_deserializer=messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAllowedUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAllowedUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreezeChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChat,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.CreateChatRequest.FromString,
                    response_serializer=messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.SerializeToString,
            ),
            'GetChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChat,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.GetChatRequest.FromString,
                    response_serializer=messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.SerializeToString,
            ),
            'AddAllowedUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAllowedUser,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.AddAllowedUserRequest.FromString,
                    response_serializer=messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.SerializeToString,
            ),
            'RemoveAllowedUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAllowedUser,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.RemoveAllowedUserRequest.FromString,
                    response_serializer=common_dot_types__pb2.Empty.SerializeToString,
            ),
            'FreezeChat': grpc.unary_unary_rpc_method_handler(
                    servicer.FreezeChat,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.FreezeChatRequest.FromString,
                    response_serializer=messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akiora.messenger.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('akiora.messenger.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.ChatService/CreateChat',
            messenger_dot_v1_dot_messenger__service__pb2.CreateChatRequest.SerializeToString,
            messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.ChatService/GetChat',
            messenger_dot_v1_dot_messenger__service__pb2.GetChatRequest.SerializeToString,
            messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAllowedUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.ChatService/AddAllowedUser',
            messenger_dot_v1_dot_messenger__service__pb2.AddAllowedUserRequest.SerializeToString,
            messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAllowedUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.ChatService/RemoveAllowedUser',
            messenger_dot_v1_dot_messenger__service__pb2.RemoveAllowedUserRequest.SerializeToString,
            common_dot_types__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FreezeChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.ChatService/FreezeChat',
            messenger_dot_v1_dot_messenger__service__pb2.FreezeChatRequest.SerializeToString,
            messenger_dot_v1_dot_messenger__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/akiora.messenger.MessageService/SendMessage',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/akiora.messenger.MessageService/GetMessages',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=messenger_dot_v1_dot_messenger__service__pb2.GetMessagesResponse.FromString,
                _registered_method=True)
        self.UpdateMessage = channel.unary_unary(
                '/akiora.messenger.MessageService/UpdateMessage',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.UpdateMessageRequest.SerializeToString,
                response_deserializer=messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.DeleteMessage = channel.unary_unary(
                '/akiora.messenger.MessageService/DeleteMessage',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.DeleteMessageRequest.SerializeToString,
                response_deserializer=common_dot_types__pb2.Empty.FromString,
                _registered_method=True)
        self.MarkAsRead = channel.unary_unary(
                '/akiora.messenger.MessageService/MarkAsRead',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.MarkAsReadRequest.SerializeToString,
                response_deserializer=messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.AddReaction = channel.unary_unary(
                '/akiora.messenger.MessageService/AddReaction',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.AddReactionRequest.SerializeToString,
                response_deserializer=messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.RemoveReaction = channel.unary_unary(
                '/akiora.messenger.MessageService/RemoveReaction',
                request_serializer=messenger_dot_v1_dot_messenger__service__pb2.RemoveReactionRequest.SerializeToString,
                response_deserializer=common_dot_types__pb2.Empty.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkAsRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddReaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveReaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.SendMessageRequest.FromString,
                    response_serializer=messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.GetMessagesRequest.FromString,
                    response_serializer=messenger_dot_v1_dot_messenger__service__pb2.GetMessagesResponse.SerializeToString,
            ),
            'UpdateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMessage,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.UpdateMessageRequest.FromString,
                    response_serializer=messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.DeleteMessageRequest.FromString,
                    response_serializer=common_dot_types__pb2.Empty.SerializeToString,
            ),
            'MarkAsRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkAsRead,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.MarkAsReadRequest.FromString,
                    response_serializer=messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.SerializeToString,
            ),
            'AddReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReaction,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.AddReactionRequest.FromString,
                    response_serializer=messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.SerializeToString,
            ),
            'RemoveReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveReaction,
                    request_deserializer=messenger_dot_v1_dot_messenger__service__pb2.RemoveReactionRequest.FromString,
                    response_serializer=common_dot_types__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akiora.messenger.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('akiora.messenger.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.MessageService/SendMessage',
            messenger_dot_v1_dot_messenger__service__pb2.SendMessageRequest.SerializeToString,
            messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.MessageService/GetMessages',
            messenger_dot_v1_dot_messenger__service__pb2.GetMessagesRequest.SerializeToString,
            messenger_dot_v1_dot_messenger__service__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.MessageService/UpdateMessage',
            messenger_dot_v1_dot_messenger__service__pb2.UpdateMessageRequest.SerializeToString,
            messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.MessageService/DeleteMessage',
            messenger_dot_v1_dot_messenger__service__pb2.DeleteMessageRequest.SerializeToString,
            common_dot_types__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkAsRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.MessageService/MarkAsRead',
            messenger_dot_v1_dot_messenger__service__pb2.MarkAsReadRequest.SerializeToString,
            messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.MessageService/AddReaction',
            messenger_dot_v1_dot_messenger__service__pb2.AddReactionRequest.SerializeToString,
            messenger_dot_v1_dot_messenger__service__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.messenger.MessageService/RemoveReaction',
            messenger_dot_v1_dot_messenger__service__pb2.RemoveReactionRequest.SerializeToString,
            common_dot_types__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
