# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: community/club/v1/club_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'community/club/v1/club_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$community/club/v1/club_service.proto\x12\x15\x61kiora.community.club\"3\n\x11\x43reateClubRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"[\n\x10PatchClubRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tadd_users\x18\x03 \x03(\t\x12\x14\n\x0c\x64\x65lete_users\x18\x04 \x03(\t\"I\n\x0c\x43lubResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05users\x18\x04 \x03(\t\"\x1c\n\x0eGetClubRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x9d\x02\n\x0b\x43lubService\x12[\n\nCreateClub\x12(.akiora.community.club.CreateClubRequest\x1a#.akiora.community.club.ClubResponse\x12Z\n\nUpdateClub\x12\'.akiora.community.club.PatchClubRequest\x1a#.akiora.community.club.ClubResponse\x12U\n\x07GetClub\x12%.akiora.community.club.GetClubRequest\x1a#.akiora.community.club.ClubResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'community.club.v1.club_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECLUBREQUEST']._serialized_start=63
  _globals['_CREATECLUBREQUEST']._serialized_end=114
  _globals['_PATCHCLUBREQUEST']._serialized_start=116
  _globals['_PATCHCLUBREQUEST']._serialized_end=207
  _globals['_CLUBRESPONSE']._serialized_start=209
  _globals['_CLUBRESPONSE']._serialized_end=282
  _globals['_GETCLUBREQUEST']._serialized_start=284
  _globals['_GETCLUBREQUEST']._serialized_end=312
  _globals['_CLUBSERVICE']._serialized_start=315
  _globals['_CLUBSERVICE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
