# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.api.expr.conformance.v1alpha1 import conformance_service_pb2 as google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/api/expr/conformance/v1alpha1/conformance_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConformanceServiceStub(object):
    """Access a CEL implementation from another process or machine.
    A CEL implementation is decomposed as a parser, a static checker,
    and an evaluator.  Every CEL implementation is expected to provide
    a server for this API.  The API will be used for conformance testing
    and other utilities.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Parse = channel.unary_unary(
                '/google.api.expr.conformance.v1alpha1.ConformanceService/Parse',
                request_serializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.ParseRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/google.api.expr.conformance.v1alpha1.ConformanceService/Check',
                request_serializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.CheckRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.Eval = channel.unary_unary(
                '/google.api.expr.conformance.v1alpha1.ConformanceService/Eval',
                request_serializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.EvalRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.EvalResponse.FromString,
                _registered_method=True)


class ConformanceServiceServicer(object):
    """Access a CEL implementation from another process or machine.
    A CEL implementation is decomposed as a parser, a static checker,
    and an evaluator.  Every CEL implementation is expected to provide
    a server for this API.  The API will be used for conformance testing
    and other utilities.
    """

    def Parse(self, request, context):
        """Transforms CEL source text into a parsed representation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Runs static checks on a parsed CEL representation and return
        an annotated representation, or a set of issues.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Eval(self, request, context):
        """Evaluates a parsed or annotation CEL representation given
        values of external bindings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConformanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.ParseRequest.FromString,
                    response_serializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.ParseResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.CheckRequest.FromString,
                    response_serializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.CheckResponse.SerializeToString,
            ),
            'Eval': grpc.unary_unary_rpc_method_handler(
                    servicer.Eval,
                    request_deserializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.EvalRequest.FromString,
                    response_serializer=google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.EvalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.api.expr.conformance.v1alpha1.ConformanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.api.expr.conformance.v1alpha1.ConformanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConformanceService(object):
    """Access a CEL implementation from another process or machine.
    A CEL implementation is decomposed as a parser, a static checker,
    and an evaluator.  Every CEL implementation is expected to provide
    a server for this API.  The API will be used for conformance testing
    and other utilities.
    """

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.expr.conformance.v1alpha1.ConformanceService/Parse',
            google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.ParseRequest.SerializeToString,
            google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.expr.conformance.v1alpha1.ConformanceService/Check',
            google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.CheckRequest.SerializeToString,
            google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Eval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.expr.conformance.v1alpha1.ConformanceService/Eval',
            google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.EvalRequest.SerializeToString,
            google_dot_api_dot_expr_dot_conformance_dot_v1alpha1_dot_conformance__service__pb2.EvalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
