# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.api.servicecontrol.v1 import service_controller_pb2 as google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/api/servicecontrol/v1/service_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceControllerStub(object):
    """[Google Service Control API](/service-control/overview)

    Lets clients check and report operations against a [managed
    service](https://cloud.google.com/service-management/reference/rpc/google.api/servicemanagement.v1#google.api.servicemanagement.v1.ManagedService).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/google.api.servicecontrol.v1.ServiceController/Check',
                request_serializer=google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.CheckRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.Report = channel.unary_unary(
                '/google.api.servicecontrol.v1.ServiceController/Report',
                request_serializer=google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.ReportRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.ReportResponse.FromString,
                _registered_method=True)


class ServiceControllerServicer(object):
    """[Google Service Control API](/service-control/overview)

    Lets clients check and report operations against a [managed
    service](https://cloud.google.com/service-management/reference/rpc/google.api/servicemanagement.v1#google.api.servicemanagement.v1.ManagedService).
    """

    def Check(self, request, context):
        """Checks whether an operation on a service should be allowed to proceed
        based on the configuration of the service and related policies. It must be
        called before the operation is executed.

        If feasible, the client should cache the check results and reuse them for
        60 seconds. In case of any server errors, the client should rely on the
        cached results for much longer time to avoid outage.
        WARNING: There is general 60s delay for the configuration and policy
        propagation, therefore callers MUST NOT depend on the `Check` method having
        the latest policy information.

        NOTE: the [CheckRequest][google.api.servicecontrol.v1.CheckRequest] has
        the size limit (wire-format byte size) of 1MB.

        This method requires the `servicemanagement.services.check` permission
        on the specified service. For more information, see
        [Cloud IAM](https://cloud.google.com/iam).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Report(self, request, context):
        """Reports operation results to Google Service Control, such as logs and
        metrics. It should be called after an operation is completed.

        If feasible, the client should aggregate reporting data for up to 5
        seconds to reduce API traffic. Limiting aggregation to 5 seconds is to
        reduce data loss during client crashes. Clients should carefully choose
        the aggregation time window to avoid data loss risk more than 0.01%
        for business and compliance reasons.

        NOTE: the [ReportRequest][google.api.servicecontrol.v1.ReportRequest] has
        the size limit (wire-format byte size) of 1MB.

        This method requires the `servicemanagement.services.report` permission
        on the specified service. For more information, see
        [Google Cloud IAM](https://cloud.google.com/iam).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.CheckRequest.FromString,
                    response_serializer=google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.CheckResponse.SerializeToString,
            ),
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.ReportRequest.FromString,
                    response_serializer=google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.ReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.api.servicecontrol.v1.ServiceController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.api.servicecontrol.v1.ServiceController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceController(object):
    """[Google Service Control API](/service-control/overview)

    Lets clients check and report operations against a [managed
    service](https://cloud.google.com/service-management/reference/rpc/google.api/servicemanagement.v1#google.api.servicemanagement.v1.ManagedService).
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.servicecontrol.v1.ServiceController/Check',
            google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.CheckRequest.SerializeToString,
            google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.servicecontrol.v1.ServiceController/Report',
            google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.ReportRequest.SerializeToString,
            google_dot_api_dot_servicecontrol_dot_v1_dot_service__controller__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
