# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.api.servicecontrol.v2 import service_controller_pb2 as google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/api/servicecontrol/v2/service_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceControllerStub(object):
    """[Service Control API
    v2](https://cloud.google.com/service-infrastructure/docs/service-control/access-control)

    This API provides admission control and telemetry reporting for services
    that are integrated with [Service
    Infrastructure](https://cloud.google.com/service-infrastructure).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/google.api.servicecontrol.v2.ServiceController/Check',
                request_serializer=google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.CheckRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.Report = channel.unary_unary(
                '/google.api.servicecontrol.v2.ServiceController/Report',
                request_serializer=google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.ReportRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.ReportResponse.FromString,
                _registered_method=True)


class ServiceControllerServicer(object):
    """[Service Control API
    v2](https://cloud.google.com/service-infrastructure/docs/service-control/access-control)

    This API provides admission control and telemetry reporting for services
    that are integrated with [Service
    Infrastructure](https://cloud.google.com/service-infrastructure).
    """

    def Check(self, request, context):
        """This method provides admission control for services that are integrated
        with [Service
        Infrastructure](https://cloud.google.com/service-infrastructure). It checks
        whether an operation should be allowed based on the service configuration
        and relevant policies. It must be called before the operation is executed.
        For more information, see
        [Admission
        Control](https://cloud.google.com/service-infrastructure/docs/admission-control).

        NOTE: The admission control has an expected policy propagation delay of
        60s. The caller **must** not depend on the most recent policy changes.

        NOTE: The admission control has a hard limit of 1 referenced resources
        per call. If an operation refers to more than 1 resources, the caller
        must call the Check method multiple times.

        This method requires the `servicemanagement.services.check` permission
        on the specified service. For more information, see
        [Service Control API Access
        Control](https://cloud.google.com/service-infrastructure/docs/service-control/access-control).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Report(self, request, context):
        """This method provides telemetry reporting for services that are integrated
        with [Service
        Infrastructure](https://cloud.google.com/service-infrastructure). It
        reports a list of operations that have occurred on a service. It must be
        called after the operations have been executed. For more information, see
        [Telemetry
        Reporting](https://cloud.google.com/service-infrastructure/docs/telemetry-reporting).

        NOTE: The telemetry reporting has a hard limit of 100 operations and 1MB
        per Report call.

        This method requires the `servicemanagement.services.report` permission
        on the specified service. For more information, see
        [Service Control API Access
        Control](https://cloud.google.com/service-infrastructure/docs/service-control/access-control).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.CheckRequest.FromString,
                    response_serializer=google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.CheckResponse.SerializeToString,
            ),
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.ReportRequest.FromString,
                    response_serializer=google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.ReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.api.servicecontrol.v2.ServiceController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.api.servicecontrol.v2.ServiceController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceController(object):
    """[Service Control API
    v2](https://cloud.google.com/service-infrastructure/docs/service-control/access-control)

    This API provides admission control and telemetry reporting for services
    that are integrated with [Service
    Infrastructure](https://cloud.google.com/service-infrastructure).
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.servicecontrol.v2.ServiceController/Check',
            google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.CheckRequest.SerializeToString,
            google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.servicecontrol.v2.ServiceController/Report',
            google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.ReportRequest.SerializeToString,
            google_dot_api_dot_servicecontrol_dot_v2_dot_service__controller__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
