# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.api.servicecontrol.v1 import quota_controller_pb2 as google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/api/servicecontrol/v1/quota_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuotaControllerStub(object):
    """[Google Quota Control API](/service-control/overview)

    Allows clients to allocate and release quota against a [managed
    service](https://cloud.google.com/service-management/reference/rpc/google.api/servicemanagement.v1#google.api.servicemanagement.v1.ManagedService).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AllocateQuota = channel.unary_unary(
                '/google.api.servicecontrol.v1.QuotaController/AllocateQuota',
                request_serializer=google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2.AllocateQuotaRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2.AllocateQuotaResponse.FromString,
                _registered_method=True)


class QuotaControllerServicer(object):
    """[Google Quota Control API](/service-control/overview)

    Allows clients to allocate and release quota against a [managed
    service](https://cloud.google.com/service-management/reference/rpc/google.api/servicemanagement.v1#google.api.servicemanagement.v1.ManagedService).
    """

    def AllocateQuota(self, request, context):
        """Attempts to allocate quota for the specified consumer. It should be called
        before the operation is executed.

        This method requires the `servicemanagement.services.quota`
        permission on the specified service. For more information, see
        [Cloud IAM](https://cloud.google.com/iam).

        **NOTE:** The client **must** fail-open on server errors `INTERNAL`,
        `UNKNOWN`, `DEADLINE_EXCEEDED`, and `UNAVAILABLE`. To ensure system
        reliability, the server may inject these errors to prohibit any hard
        dependency on the quota functionality.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuotaControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AllocateQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateQuota,
                    request_deserializer=google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2.AllocateQuotaRequest.FromString,
                    response_serializer=google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2.AllocateQuotaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.api.servicecontrol.v1.QuotaController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.api.servicecontrol.v1.QuotaController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuotaController(object):
    """[Google Quota Control API](/service-control/overview)

    Allows clients to allocate and release quota against a [managed
    service](https://cloud.google.com/service-management/reference/rpc/google.api/servicemanagement.v1#google.api.servicemanagement.v1.ManagedService).
    """

    @staticmethod
    def AllocateQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.servicecontrol.v1.QuotaController/AllocateQuota',
            google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2.AllocateQuotaRequest.SerializeToString,
            google_dot_api_dot_servicecontrol_dot_v1_dot_quota__controller__pb2.AllocateQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
