# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.api.cloudquotas.v1beta import cloudquotas_pb2 as google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2
from google.api.cloudquotas.v1beta import resources_pb2 as google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/api/cloudquotas/v1beta/cloudquotas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudQuotasStub(object):
    """The Cloud Quotas API is an infrastructure service for Google Cloud that lets
    service consumers list and manage their resource usage limits.

    - List/Get the metadata and current status of the quotas for a service.
    - Create/Update quota preferencess that declare the preferred quota values.
    - Check the status of a quota preference request.
    - List/Get pending and historical quota preference.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListQuotaInfos = channel.unary_unary(
                '/google.api.cloudquotas.v1beta.CloudQuotas/ListQuotaInfos',
                request_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaInfosRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaInfosResponse.FromString,
                _registered_method=True)
        self.GetQuotaInfo = channel.unary_unary(
                '/google.api.cloudquotas.v1beta.CloudQuotas/GetQuotaInfo',
                request_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.GetQuotaInfoRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaInfo.FromString,
                _registered_method=True)
        self.ListQuotaPreferences = channel.unary_unary(
                '/google.api.cloudquotas.v1beta.CloudQuotas/ListQuotaPreferences',
                request_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaPreferencesRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaPreferencesResponse.FromString,
                _registered_method=True)
        self.GetQuotaPreference = channel.unary_unary(
                '/google.api.cloudquotas.v1beta.CloudQuotas/GetQuotaPreference',
                request_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.GetQuotaPreferenceRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaPreference.FromString,
                _registered_method=True)
        self.CreateQuotaPreference = channel.unary_unary(
                '/google.api.cloudquotas.v1beta.CloudQuotas/CreateQuotaPreference',
                request_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.CreateQuotaPreferenceRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaPreference.FromString,
                _registered_method=True)
        self.UpdateQuotaPreference = channel.unary_unary(
                '/google.api.cloudquotas.v1beta.CloudQuotas/UpdateQuotaPreference',
                request_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.UpdateQuotaPreferenceRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaPreference.FromString,
                _registered_method=True)


class CloudQuotasServicer(object):
    """The Cloud Quotas API is an infrastructure service for Google Cloud that lets
    service consumers list and manage their resource usage limits.

    - List/Get the metadata and current status of the quotas for a service.
    - Create/Update quota preferencess that declare the preferred quota values.
    - Check the status of a quota preference request.
    - List/Get pending and historical quota preference.
    """

    def ListQuotaInfos(self, request, context):
        """Lists QuotaInfos of all quotas for a given project, folder or organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuotaInfo(self, request, context):
        """Retrieve the QuotaInfo of a quota for a project, folder or organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListQuotaPreferences(self, request, context):
        """Lists QuotaPreferences in a given project, folder or organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuotaPreference(self, request, context):
        """Gets details of a single QuotaPreference.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateQuotaPreference(self, request, context):
        """Creates a new QuotaPreference that declares the desired value for a quota.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateQuotaPreference(self, request, context):
        """Updates the parameters of a single QuotaPreference. It can updates the
        config in any states, not just the ones pending approval.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudQuotasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListQuotaInfos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQuotaInfos,
                    request_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaInfosRequest.FromString,
                    response_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaInfosResponse.SerializeToString,
            ),
            'GetQuotaInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuotaInfo,
                    request_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.GetQuotaInfoRequest.FromString,
                    response_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaInfo.SerializeToString,
            ),
            'ListQuotaPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQuotaPreferences,
                    request_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaPreferencesRequest.FromString,
                    response_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaPreferencesResponse.SerializeToString,
            ),
            'GetQuotaPreference': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuotaPreference,
                    request_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.GetQuotaPreferenceRequest.FromString,
                    response_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaPreference.SerializeToString,
            ),
            'CreateQuotaPreference': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQuotaPreference,
                    request_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.CreateQuotaPreferenceRequest.FromString,
                    response_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaPreference.SerializeToString,
            ),
            'UpdateQuotaPreference': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQuotaPreference,
                    request_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.UpdateQuotaPreferenceRequest.FromString,
                    response_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaPreference.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.api.cloudquotas.v1beta.CloudQuotas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.api.cloudquotas.v1beta.CloudQuotas', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudQuotas(object):
    """The Cloud Quotas API is an infrastructure service for Google Cloud that lets
    service consumers list and manage their resource usage limits.

    - List/Get the metadata and current status of the quotas for a service.
    - Create/Update quota preferencess that declare the preferred quota values.
    - Check the status of a quota preference request.
    - List/Get pending and historical quota preference.
    """

    @staticmethod
    def ListQuotaInfos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.cloudquotas.v1beta.CloudQuotas/ListQuotaInfos',
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaInfosRequest.SerializeToString,
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaInfosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuotaInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.cloudquotas.v1beta.CloudQuotas/GetQuotaInfo',
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.GetQuotaInfoRequest.SerializeToString,
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListQuotaPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.cloudquotas.v1beta.CloudQuotas/ListQuotaPreferences',
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaPreferencesRequest.SerializeToString,
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.ListQuotaPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuotaPreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.cloudquotas.v1beta.CloudQuotas/GetQuotaPreference',
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.GetQuotaPreferenceRequest.SerializeToString,
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaPreference.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateQuotaPreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.cloudquotas.v1beta.CloudQuotas/CreateQuotaPreference',
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.CreateQuotaPreferenceRequest.SerializeToString,
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaPreference.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateQuotaPreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.cloudquotas.v1beta.CloudQuotas/UpdateQuotaPreference',
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_cloudquotas__pb2.UpdateQuotaPreferenceRequest.SerializeToString,
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_resources__pb2.QuotaPreference.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
