# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.api.cloudquotas.v1beta import quota_adjuster_settings_pb2 as google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/api/cloudquotas/v1beta/quota_adjuster_settings_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuotaAdjusterSettingsManagerStub(object):
    """The Quotas Adjuster Settings API is an infrastructure service for Google
    Cloud that lets service consumers view and update their quota adjuster
    settings.

    - Update quota adjuster settings.
    - Get the name of the configurations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateQuotaAdjusterSettings = channel.unary_unary(
                '/google.api.cloudquotas.v1beta.QuotaAdjusterSettingsManager/UpdateQuotaAdjusterSettings',
                request_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.UpdateQuotaAdjusterSettingsRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.QuotaAdjusterSettings.FromString,
                _registered_method=True)
        self.GetQuotaAdjusterSettings = channel.unary_unary(
                '/google.api.cloudquotas.v1beta.QuotaAdjusterSettingsManager/GetQuotaAdjusterSettings',
                request_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.GetQuotaAdjusterSettingsRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.QuotaAdjusterSettings.FromString,
                _registered_method=True)


class QuotaAdjusterSettingsManagerServicer(object):
    """The Quotas Adjuster Settings API is an infrastructure service for Google
    Cloud that lets service consumers view and update their quota adjuster
    settings.

    - Update quota adjuster settings.
    - Get the name of the configurations.
    """

    def UpdateQuotaAdjusterSettings(self, request, context):
        """Updates the QuotaAdjusterSettings for the specified resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuotaAdjusterSettings(self, request, context):
        """Gets the QuotaAdjusterSettings for the specified resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuotaAdjusterSettingsManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateQuotaAdjusterSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQuotaAdjusterSettings,
                    request_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.UpdateQuotaAdjusterSettingsRequest.FromString,
                    response_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.QuotaAdjusterSettings.SerializeToString,
            ),
            'GetQuotaAdjusterSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuotaAdjusterSettings,
                    request_deserializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.GetQuotaAdjusterSettingsRequest.FromString,
                    response_serializer=google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.QuotaAdjusterSettings.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.api.cloudquotas.v1beta.QuotaAdjusterSettingsManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.api.cloudquotas.v1beta.QuotaAdjusterSettingsManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuotaAdjusterSettingsManager(object):
    """The Quotas Adjuster Settings API is an infrastructure service for Google
    Cloud that lets service consumers view and update their quota adjuster
    settings.

    - Update quota adjuster settings.
    - Get the name of the configurations.
    """

    @staticmethod
    def UpdateQuotaAdjusterSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.cloudquotas.v1beta.QuotaAdjusterSettingsManager/UpdateQuotaAdjusterSettings',
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.UpdateQuotaAdjusterSettingsRequest.SerializeToString,
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.QuotaAdjusterSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuotaAdjusterSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.api.cloudquotas.v1beta.QuotaAdjusterSettingsManager/GetQuotaAdjusterSettings',
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.GetQuotaAdjusterSettingsRequest.SerializeToString,
            google_dot_api_dot_cloudquotas_dot_v1beta_dot_quota__adjuster__settings__pb2.QuotaAdjusterSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
