# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from community.club.v1 import club_service_pb2 as community_dot_club_dot_v1_dot_club__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in community/club/v1/club_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClubServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateClub = channel.unary_unary(
                '/akiora.community.club.ClubService/CreateClub',
                request_serializer=community_dot_club_dot_v1_dot_club__service__pb2.CreateClubRequest.SerializeToString,
                response_deserializer=community_dot_club_dot_v1_dot_club__service__pb2.ClubResponse.FromString,
                _registered_method=True)
        self.UpdateClub = channel.unary_unary(
                '/akiora.community.club.ClubService/UpdateClub',
                request_serializer=community_dot_club_dot_v1_dot_club__service__pb2.PatchClubRequest.SerializeToString,
                response_deserializer=community_dot_club_dot_v1_dot_club__service__pb2.ClubResponse.FromString,
                _registered_method=True)
        self.GetClub = channel.unary_unary(
                '/akiora.community.club.ClubService/GetClub',
                request_serializer=community_dot_club_dot_v1_dot_club__service__pb2.GetClubRequest.SerializeToString,
                response_deserializer=community_dot_club_dot_v1_dot_club__service__pb2.ClubResponse.FromString,
                _registered_method=True)


class ClubServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateClub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClubServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateClub': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClub,
                    request_deserializer=community_dot_club_dot_v1_dot_club__service__pb2.CreateClubRequest.FromString,
                    response_serializer=community_dot_club_dot_v1_dot_club__service__pb2.ClubResponse.SerializeToString,
            ),
            'UpdateClub': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClub,
                    request_deserializer=community_dot_club_dot_v1_dot_club__service__pb2.PatchClubRequest.FromString,
                    response_serializer=community_dot_club_dot_v1_dot_club__service__pb2.ClubResponse.SerializeToString,
            ),
            'GetClub': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClub,
                    request_deserializer=community_dot_club_dot_v1_dot_club__service__pb2.GetClubRequest.FromString,
                    response_serializer=community_dot_club_dot_v1_dot_club__service__pb2.ClubResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akiora.community.club.ClubService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('akiora.community.club.ClubService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClubService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateClub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.community.club.ClubService/CreateClub',
            community_dot_club_dot_v1_dot_club__service__pb2.CreateClubRequest.SerializeToString,
            community_dot_club_dot_v1_dot_club__service__pb2.ClubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateClub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.community.club.ClubService/UpdateClub',
            community_dot_club_dot_v1_dot_club__service__pb2.PatchClubRequest.SerializeToString,
            community_dot_club_dot_v1_dot_club__service__pb2.ClubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akiora.community.club.ClubService/GetClub',
            community_dot_club_dot_v1_dot_club__service__pb2.GetClubRequest.SerializeToString,
            community_dot_club_dot_v1_dot_club__service__pb2.ClubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
